### ISSUE TITLE
Call to a member function get() on null ($this->translations)

### ISSUE THREAD

**Issue by Gregor2203** [odiseoteam/SyliusBlogPlugin#20]
Hello
 I extended class ArticleCategory and it works, but if I trying add new article got error "Call to a member function get() on null".
This $this->translations, initialised in constructor (TranslatableTrait), return NULL. It's weird.
```
public function __construct()
    {
        $this->translations = new ArrayCollection();
    }
```

My model:
```
declare(strict_types=1);

namespace App\Entity\Blog;

use Doctrine\ORM\Mapping as ORM;
use Odiseo\BlogBundle\Model\ArticleCategory as BaseArticleCategory;
use Odiseo\BlogBundle\Model\ArticleCategoryTranslation;
use Odiseo\BlogBundle\Model\ArticleCategoryInterface;

/**
 * @ORM\Entity
 * @ORM\Table(name="odiseo_blog_article_category")
 */
class ArticleCategory extends BaseArticleCategory implements ArticleCategoryInterface
{
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $wp_id;

    /**
     * @ORM\ManyToOne(targetEntity=ArticleCategory::class)
	 * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $parent;

    public function getWpId(): ?int
    {
        return $this->wp_id;
    }

    public function setWpId(int $wp_id): self
    {
        $this->wp_id = $wp_id;

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }
	
	protected function createTranslation(): ArticleCategoryTranslation
    {
        return new ArticleCategoryTranslation();
    }
}
```

odiseo_blog.yaml
```
imports:    
    - { resource: "@OdiseoSyliusBlogPlugin/Resources/config/config.yaml" }

odiseo_blog:
    resources:
        article_category:
            classes:
                model: App\Entity\Blog\ArticleCategory
```
![2021-12-16_00-24-55](https://user-images.githubusercontent.com/40366714/146281817-2d7240a8-a88f-4b3a-accb-c24e176a25d0.png)

Thanks in advance for any help!
